### ISSUE TITLE
Change VisContainer API

### ISSUE THREAD

**Issue by skodapetr** [matejikj/similarity_visualisation#22]
Instead of VisContainer handling the addition of new datasets, and then reporting URL and Collection, it would just emit event announcing that user-requested a change of a dataset. 

Thus the selection of a new dataset can be handled by the parent component. This is required as the dataset-similarity app has a custom "Add dataset dialog".

**Comment by skodapetr** [comment]
The same hold for "add paths". 

In fact, I would say, that you should should split the component into several others. So I can provide custom dialogs (select dataset, select path, .. ), custom menu, and custom visual selection (cycle, tree).

**Comment by matejikj** [comment]
How do you suggest me split that component? Separate dialogs for adding a dataset?
